export const actionTypes = {
  GET_ITEMS: "GET_ITEMS",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  GET_ITEM: "GET_ITEM",
  FILTER_ITEMS: "FILTER_ITEMS",
  SORT_ITEMS: "SORT_ITEMS",
  UPDATE_ITEM: "UPDATE_ITEM",
};
